# Generated by Django 4.2.1 on 2023-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
