# Generated by Django 4.2.1 on 2023-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(db_column='id_noticia', primary_key=True, serialize=False)),
                ('titulo_noticia', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
