# Generated by Django 4.2.1 on 2023-05-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0002_noticias_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
