# Generated by Django 4.2.1 on 2023-06-27 07:38

import CaosNewsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0009_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=CaosNewsApp.models.Noticia.get_image_upload_path),
        ),
    ]
