# Generated by Django 5.1.7 on 2025-06-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0027_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(db_column='id_plan', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('caracteristicas', models.TextField(blank=True, default='', help_text='Una característica por línea')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='PrecioPlan',
            fields=[
                ('id_precio', models.AutoField(db_column='id_precio', primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(help_text='Nombre del período (ej: Mensual, Trimestral, Semestral, Anual, etc.)', max_length=50)),
                ('duracion_dias', models.PositiveIntegerField(help_text='Duración en días del período de suscripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='CaosNewsApp.plan')),
            ],
            options={
                'verbose_name': 'Precio de Plan',
                'verbose_name_plural': 'Precios de Planes',
                'ordering': ['plan', 'duracion_dias'],
                'unique_together': {('plan', 'nombre_periodo')},
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(db_column='id_suscripcion', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('V', 'Vencida'), ('C', 'Cancelada'), ('P', 'Pendiente')], default='A', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CaosNewsApp.plan')),
                ('precio_plan', models.ForeignKey(help_text='Precio específico pagado', on_delete=django.db.models.deletion.PROTECT, to='CaosNewsApp.precioplan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
