# Generated by Django 5.1.7 on 2025-06-14 15:36

from django.db import migrations


def crear_planes_y_precios_produccion(apps, schema_editor):
    """Crear planes y precios básicos de producción"""
    plan_model = apps.get_model('CaosNewsApp', 'Plan')
    precio_plan_model = apps.get_model('CaosNewsApp', 'PrecioPlan')

    # Plan Básico
    plan_basico, created = plan_model.objects.get_or_create(
        nombre='Plan Básico',
        defaults={
            'descripcion': 'Plan básico con acceso limitado a noticias básicas',
            'caracteristicas': '''Acceso limitado ✔️
Noticias básicas ✔️
Sin Publicidad ❌
Videos ❌
Audios ❌
Noticias en tiempo real ❌
Noticias exclusivas ❌''',
            'activo': True,
        }
    )

    if created:
        # Precios para Plan Básico
        precio_plan_model.objects.create(
            plan=plan_basico,
            nombre_periodo='Mensual',
            duracion_dias=30,
            valor=2990.00,
            activo=True
        )
        precio_plan_model.objects.create(
            plan=plan_basico,
            nombre_periodo='Anual',
            duracion_dias=365,
            valor=29990.00,
            activo=True
        )

    # Plan Estándar
    plan_estandar, created = plan_model.objects.get_or_create(
        nombre='Plan Estandar',
        defaults={
            'descripcion': 'Plan estándar con contenido audiovisual adicional',
            'caracteristicas': '''Acceso limitado ✔️
Noticias básicas ✔️
Sin Publicidad ✔️
Videos ✔️
Audios ✔️
Noticias en tiempo real ❌
Noticias exclusivas ❌''',
            'activo': True,
        }
    )

    if created:
        # Precios para Plan Estándar
        precio_plan_model.objects.create(
            plan=plan_estandar,
            nombre_periodo='Mensual',
            duracion_dias=30,
            valor=4990.00,
            activo=True
        )
        precio_plan_model.objects.create(
            plan=plan_estandar,
            nombre_periodo='Anual',
            duracion_dias=365,
            valor=49990.00,
            activo=True
        )

    # Plan Premium
    plan_premium, created = plan_model.objects.get_or_create(
        nombre='Plan Premium',
        defaults={
            'descripcion': 'Plan premium con acceso completo y contenido exclusivo',
            'caracteristicas': '''Acceso ilimitado ✔️
Noticias básicas ✔️
Sin Publicidad ✔️
Videos ✔️
Audios ✔️
Noticias en tiempo real ✔️
Noticias exclusivas ✔️''',
            'activo': True,
        }
    )

    if created:
        # Precios para Plan Premium
        precio_plan_model.objects.create(
            plan=plan_premium,
            nombre_periodo='Mensual',
            duracion_dias=30,
            valor=8990.00,
            activo=True
        )
        precio_plan_model.objects.create(
            plan=plan_premium,
            nombre_periodo='Anual',
            duracion_dias=365,
            valor=89990.00,
            activo=True
        )


def eliminar_planes_produccion(apps, schema_editor):
    """Eliminar planes de producción (rollback)"""
    plan_model = apps.get_model('CaosNewsApp', 'Plan')
    plan_model.objects.filter(nombre__in=['Plan Básico', 'Plan Estandar', 'Plan Premium']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0028_plan_precioplan_suscripcion'),
    ]

    operations = [
        migrations.RunPython(crear_planes_y_precios_produccion, eliminar_planes_produccion),
    ]
